on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.2 # Actualizar a una versión que use Node.js 16
      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0 # Actualizar a una versión que use Node.js 16
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0 # Actualizar a una versión que use Node.js 16
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apirestscrapybinance:${{ github.sha }}

